routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth','namespace' => 'Web'], static function() {
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('kategori', 'KategoriController');
    Route::get('kategori/delete/{kategori}','KategoriController@delete')->name('kategori.delete');

    Route::resource('transaksi', 'TransaksiController');
    Route::get('transaksi/delete/{transaksi}','TransaksiController@delete')->name('transaksi.delete');
});

app/Transaksi.php
<?php

namespace App;

use App\Scopes\UserScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Transaksi extends Model
{
    protected $fillable = [
      'tanggal_transaksi',
      'jenis_transaksi',
      'nominal',
      'deskripsi'
    ];

    protected static function boot(): void
    {
        parent::boot();
        static::addGlobalScope(new UserScope());
    }

    /**
     * @return BelongsTo
     */
    public function kategori(){
        return $this->belongsTo(Kategori::class);
    }

    /**
     * @return BelongsTo
     */
    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Web/TransaksiController.php
<?php

namespace App\Http\Controllers\Web;

use App\Constants\JenisKategori;
use App\Kategori;
use App\Services\AccountingService;
use App\Transaksi;
use Carbon\Carbon;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Zend\Diactoros\Response\TextResponse;

class TransaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $accountingService = new AccountingService();
        $saldo = $accountingService->getCurrentSaldo();

        $today = date("Y-m-d");
        $startDateOfThisMonth = date('Y-m-01', strtotime($today));
        $endDateOfThisMonth = date('Y-m-t', strtotime($today));

        $startDate = $request->has('start_date')
            ? $request->get('start_date')
            :  $startDateOfThisMonth;

        $endDate = $request->has('end_date')
            ?  $request->get('end_date')
            : $endDateOfThisMonth;

        $transaksis = Transaksi::whereBetween('tanggal_transaksi',[Carbon::parse($startDate)->startOfDay(), Carbon::parse($endDate)->endOfDay()])
                    ->paginate(5)
                    ->appends($request->all());

        return view('transaksi.index', compact('transaksis', 'saldo'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategoris = Kategori::all();
        return view('transaksi.create', compact('kategoris'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request,[
           'tanggal_transaksi' => 'required',
           'jenis_transaksi' => 'required',
           'kategori_id' => 'required',
           'nominal' => 'required',
           'deskripsi' => 'required'
        ]);

        $kategori = Kategori::find($request->get('kategori_id'));
        if($kategori->jenis_kategori !== $request->get('jenis_transaksi')){
             flash('Kategori yang dimasukkan tidak sesuai dengan jenis transaksi!')->warning();
             return redirect()->back();
        }

        $transaksi = new Transaksi();
        $transaksi->fill($request->all());
        $transaksi->user()->associate($request->user());
        $transaksi->kategori()->associate($kategori);
        $transaksi->save()
            ? flash('Transaksi berhasil disimpan!')->success()
            : flash('Transaksi gagal disimpan!')->error();

        return redirect()->route('transaksi.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Transaksi $transaksi
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaksi $transaksi)
    {
        $kategoris = Kategori::all();
        return view('transaksi.edit', compact('kategoris','transaksi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Transaksi $transaksi
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Transaksi $transaksi)
    {
        $this->validate($request,[
            'tanggal_transaksi' => 'required',
            'jenis_transaksi' => 'required',
            'kategori_id' => 'required',
            'nominal' => 'required',
            'deskripsi' => 'required'
        ]);

        $kategori = Kategori::find($request->get('kategori_id'));
        if($kategori->jenis_kategori !== $request->get('jenis_transaksi')){
            flash('Kategori yang dimasukkan tidak sesuai dengan jenis transaksi!')->warning();
            return redirect()->back();
        }

        $transaksi->fill($request->all());
        $transaksi->user()->associate($request->user());
        $transaksi->kategori()->associate($kategori);
        $transaksi->update()
            ? flash('Transaksi berhasil diubah!')->success()
            : flash('Transaksi gagal diubah!')->error();

        return redirect()->route('transaksi.index');
    }

    /**
     * @param Transaksi $transaksi
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function delete(Transaksi $transaksi){
        $transaksi->delete()
            ? flash('Transaksi berhasil dihapus!')->success()
            : flash('Transaksi gagal dihapus')->error();

        return redirect()->route('transaksi.index');
    }
}

resources/views/transaksi/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><b>Tambah Transaksi</b></div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('transaksi.store') }}">
                            @csrf
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Tanggal Transaksi</label>
                                <input type="date" class="form-control" name="tanggal_transaksi" id="exampleFormControlInput1" placeholder="Ex: Sewa Kos" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">Jenis Transaksi</label>
                                <select name="jenis_transaksi" class="form-control" id="exampleFormControlSelect1" required>
                                    @foreach(\App\Constants\JenisKategori::all() as $key => $kategori)
                                        <option value="{{ $key }}">{{ $kategori }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">Kategori</label>
                                <select name="kategori_id" class="form-control" id="exampleFormControlSelect1" required>
                                    @foreach($kategoris as $key => $kategori)
                                        <option value="{{ $kategori->id }}">{{ $kategori->nama_kategori .'-'. \App\Constants\JenisKategori::getTitle($kategori->jenis_kategori) }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Nominal</label>
                                <input type="number" min="0" class="form-control" name="nominal" id="exampleFormControlInput1" required>
                            </div>

                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Deskripsi</label>
                                <textarea class="form-control" name="deskripsi" id="exampleFormControlTextarea1" rows="3" required></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/transaksi/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><b>Tambah Transaksi</b></div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('transaksi.update', $transaksi) }}">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Tanggal Transaksi</label>
                                <input type="date" value="{{ $transaksi->tanggal_transaksi }}" class="form-control" name="tanggal_transaksi" id="exampleFormControlInput1" placeholder="Ex: Sewa Kos" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">Jenis Transaksi</label>
                                <select name="jenis_transaksi" class="form-control" id="exampleFormControlSelect1" required>
                                    @foreach(\App\Constants\JenisKategori::all() as $key => $kategori)
                                        <option value="{{ $key }}" @if($transaksi->jenis_transaksi === $key) selected @endif>{{ $kategori }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">Kategori</label>
                                <select name="kategori_id" class="form-control" id="exampleFormControlSelect1" required>
                                    @foreach($kategoris as $key => $kategori)
                                        <option value="{{ $kategori->id }}" @if($kategori->id === $transaksi->kategori_id) selected @endif>{{ $kategori->nama_kategori .'-'. \App\Constants\JenisKategori::getTitle($kategori->jenis_kategori) }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Nominal</label>
                                <input type="number" value="{{ $transaksi->nominal }}" min="0" class="form-control" name="nominal" id="exampleFormControlInput1" required>
                            </div>

                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Deskripsi</label>
                                <textarea class="form-control" name="deskripsi" id="exampleFormControlTextarea1" rows="3" required>{{ $transaksi->deskripsi }}</textarea>
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/transaksi/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><b>Saldo Saat Ini</b></div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        {{ 'IDR'.number_format($saldo, 0, ',', '.')}}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container" style="padding-top: 20px">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><b>Transaksi</b></div>

                    <div class="card-body">
                        <form id="frmFilter" class="row mb-3 clearfix">
                            <div class="col-sm-4">
                                <input  type="date"
                                        class="form-control" name="start_date" id="from_date" placeholder="From Date"
                                        value="{{ request('start_date') ?: date('Y-m-d') }}">
                            </div>

                            <div class="col-sm-4">
                                <input  type="date"
                                        class="form-control" name="end_date" id="to_date" placeholder="To Date"
                                        value="{{ request('end_date') ?: date('Y-m-d') }}">
                            </div>

                            <div class="col-sm-4">
                                <div class="float-right">
                                    <button class="btn btn-primary"><i class="fa fa-filter"></i> Filter</button>
                                </div>
                            </div>
                        </form>

                        <a href="{{ route('transaksi.create') }}" class="btn btn-primary">Tambah Transaksi</a>
                        @if(!$transaksis->isEmpty())
                            <table class="table table-striped" style="margin-top: 20px">
                                <thead>
                                <tr>
                                    <th class="text-center" style="width: 20px">No.</th>
                                    <th>{{ __('Tanggal') }}</th>
                                    <th>{{ __('Jenis') }}</th>
                                    <th>{{ __('Kategori') }}</th>
                                    <th>{{ __('Nominal') }}</th>
                                    <th>{{ __('Deskripsi') }}</th>
                                    <th class="text-center pull-right">{{ __('Aksi') }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($transaksis as $i => $transaksi)
                                    <tr>
                                        <td>{{ $i+1 }}</td>
                                        <td>{{ $transaksi->tanggal_transaksi }}</td>
                                        <td>{{ \App\Constants\JenisKategori::getTitle($transaksi->jenis_transaksi) }}</td>
                                        <td>{{ $transaksi->kategori->nama_kategori }}</td>
                                        <td>{{ 'IDR'.number_format($transaksi->nominal, 0, ',', '.')}}</td>
                                        <td>{{ $transaksi->deskripsi }}</td>
                                        <td class="text-center pull-right" >
                                            <div class="btn-group">
                                                <a href="{{ route('transaksi.edit', $transaksi) }}" class="btn btn-warning">
                                                    Ubah
                                                </a>
                                                <a href="{{ route('transaksi.delete', $transaksi) }}" class="btn btn-danger"
                                                   onclick = "return confirm('Are you sure ?')">
                                                    Hapus
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <center>{{ $transaksis->links() }}</center>
                        @else
                            <div class="px-3 text-center" style="padding: 10px">
                                <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                                    No Data
                                </p>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection