routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth','namespace' => 'Web'], static function() {
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('kategori', 'KategoriController');
    Route::get('kategori/delete/{kategori}','KategoriController@delete')->name('kategori.delete');

    Route::resource('transaksi', 'TransaksiController');
    Route::get('transaksi/delete/{transaksi}','TransaksiController@delete')->name('transaksi.delete');
});

app/Kategori.php
<?php

namespace App;

use App\Scopes\UserScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Kategori extends Model
{
    protected $fillable = [
      'nama_kategori',
      'jenis_kategori',
      'deskripsi'
    ];

    protected static function boot(): void
    {
        parent::boot();
        static::addGlobalScope(new UserScope());
    }

    /**
     * @return HasMany
     */
    public function transaksis(){
        return $this->hasMany(Transaksi::class);
    }

    /**
     * @return BelongsTo
     */
    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Web/KategoriController.php
<?php

namespace App\Http\Controllers\Web;

use App\Kategori;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|\Illuminate\View\View
     */
    public function index()
    {
        $kategories = Kategori::orderBy('created_at')->paginate(5);

        return view('kategori.index', compact('kategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
           'nama_kategori' => 'required',
           'jenis_kategori' => 'required',
           'deskripsi' => 'required'
        ]);

        $kategori = new Kategori();
        $kategori->fill($request->all());
        $kategori->user()->associate($request->user());
        $kategori->save()
            ? flash('Data kategori berhasil disimpan!')->success()
            : flash('Data kategori gagal disimpan!')->error();

        return redirect()->route('kategori.index');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param Kategori $kategori
     * @return \Illuminate\Http\Response
     */
    public function edit(Kategori $kategori)
    {
        return view('kategori.edit', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Kategori $kategori
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Kategori $kategori)
    {
        $this->validate($request, [
            'nama_kategori' => 'required',
            'jenis_kategori' => 'required',
            'deskripsi' => 'required'
        ]);

        $kategori->fill($request->all());
        $kategori->user()->associate($request->user());
        $kategori->update()
            ? flash('Data kategori berhasil diubah!')->success()
            : flash('Data kategori gagal diubah!')->error();

        return redirect()->route('kategori.index');
    }


    /**
     * @param Kategori $kategori
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function delete(Kategori $kategori){
        if(count($kategori->transaksis) > 0){
            flash('Kategori memiliki data transaksi, data tidak bisa dihapus! ')->warning();
            return redirect()->route('kategori.index');
        }

        $kategori->delete()
            ? flash('Kategori Berhasil dihapus!')->success()
            : flash('Kategori Gagal dihapus!')->error();

        return redirect()->route('kategori.index');
    }


}

resources/views/kategori/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><b>Tambah Kategori</b></div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('kategori.store') }}">
                            @csrf
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Nama Kategori</label>
                                <input type="text" class="form-control" name="nama_kategori" id="exampleFormControlInput1" placeholder="Ex: Sewa Kos" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">Jenis Kategori</label>
                                <select name="jenis_kategori" class="form-control" id="exampleFormControlSelect1" required>
                                    @foreach(\App\Constants\JenisKategori::all() as $key => $kategori)
                                        <option value="{{ $key }}">{{ $kategori }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Deskripsi</label>
                                <textarea class="form-control" name="deskripsi" id="exampleFormControlTextarea1" rows="3" required></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/kategori/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><b>Edit Kategori</b></div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('kategori.update', $kategori) }}">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Nama Kategori</label>
                                <input type="text" class="form-control" value="{{ $kategori->nama_kategori }}" name="nama_kategori" id="exampleFormControlInput1" placeholder="Ex: Sewa Kos" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlSelect1">Jenis Kategori</label>
                                <select name="jenis_kategori" class="form-control" id="exampleFormControlSelect1" required>
                                    @foreach(\App\Constants\JenisKategori::all() as $key => $kategoritemp)
                                        <option value="{{ $key }}" @if($key ==  $kategori->jenis_kategori) selected @endif >{{ $kategoritemp }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Deskripsi</label>
                                <textarea class="form-control" name="deskripsi" id="exampleFormControlTextarea1" rows="3" required>{{ $kategori->deskripsi }}</textarea>
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/kategori/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><b>Kategori</b></div>

                    <div class="card-body">
                        <a href="{{ route('kategori.create') }}" class="btn btn-primary">Tambah Kategori</a>
                        @if(!$kategories->isEmpty())
                            <table class="table table-striped" style="margin-top: 20px">
                                <thead>
                                <tr>
                                    <th class="text-center" style="width: 20px">No.</th>
                                    <th>{{ __('Nama Kategori') }}</th>
                                    <th>{{ __('Jenis') }}</th>
                                    <th>{{ __('Deskripsi') }}</th>
                                    <th class="text-center pull-right">{{ __('Aksi') }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($kategories as $i => $kategori)
                                    <tr>
                                        <td>{{ $i+1 }}</td>
                                        <td>{{ $kategori->nama_kategori }}</td>
                                        <td>{{ \App\Constants\JenisKategori::getTitle($kategori->jenis_kategori) }}</td>
                                        <td>{{ $kategori->deskripsi }}</td>
                                        <td class="text-center pull-right" >
                                            <div class="btn-group">
                                                <a href="{{ route('kategori.edit', $kategori) }}" class="btn btn-warning">
                                                    Ubah
                                                </a>
                                                <a href="{{ route('kategori.delete', $kategori) }}" class="btn btn-danger"
                                                   onclick = "return confirm('Are you sure ?')">
                                                    Hapus
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <center>{{ $kategories->links() }}</center>
                        @else
                            <div class="px-3 text-center" style="padding: 10px">
                                <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                                    No Data
                                </p>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection